-- Criar alguns pedidos de exemplo para testar o sistema de atendente
INSERT INTO orders (
  id,
  user_id,
  status,
  total_amount,
  delivery_fee,
  payment_method,
  payment_status,
  notes,
  estimated_delivery_time,
  customer_phone,
  customer_name,
  delivery_method,
  created_at,
  updated_at
) VALUES 
(
  gen_random_uuid(),
  gen_random_uuid(),
  'pending',
  89.90,
  8.00,
  'pix',
  'pending',
  'Sem cebola na pizza margherita',
  45,
  '(11) 99999-1234',
  'João Silva',
  'delivery',
  NOW() - INTERVAL '5 minutes',
  NOW() - INTERVAL '5 minutes'
),
(
  gen_random_uuid(),
  gen_random_uuid(),
  'confirmed',
  156.50,
  8.00,
  'card',
  'paid',
  'Pizza bem assada',
  40,
  '(11) 88888-5678',
  'Maria Santos',
  'delivery',
  NOW() - INTERVAL '15 minutes',
  NOW() - INTERVAL '10 minutes'
),
(
  gen_random_uuid(),
  gen_random_uuid(),
  'preparing',
  78.30,
  0.00,
  'cash',
  'pending',
  null,
  0,
  '(11) 77777-9012',
  'Pedro Costa',
  'pickup',
  NOW() - INTERVAL '20 minutes',
  NOW() - INTERVAL '5 minutes'
),
(
  gen_random_uuid(),
  gen_random_uuid(),
  'ready',
  234.70,
  12.00,
  'pix',
  'paid',
  'Entrega no portão principal',
  35,
  '(11) 66666-3456',
  'Ana Oliveira',
  'delivery',
  NOW() - INTERVAL '35 minutes',
  NOW() - INTERVAL '2 minutes'
);